// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL7yOnqMUjA1sxuvoY1U1GtOmc5oAK3rM',
    appId: '1:681779716913:web:40fa900abd2cb021e04610',
    messagingSenderId: '681779716913',
    projectId: 'find-a-cat-78ac7',
    authDomain: 'find-a-cat-78ac7.firebaseapp.com',
    storageBucket: 'find-a-cat-78ac7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo4KaDUQRNv1yZV4EhtiGSM2i9RS2eYuk',
    appId: '1:681779716913:android:338fdfd05f3b5ad1e04610',
    messagingSenderId: '681779716913',
    projectId: 'find-a-cat-78ac7',
    storageBucket: 'find-a-cat-78ac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnBDsmWSWOoZAHTgRrKNGUKPhkmhPWF_U',
    appId: '1:681779716913:ios:03aea7eece110306e04610',
    messagingSenderId: '681779716913',
    projectId: 'find-a-cat-78ac7',
    storageBucket: 'find-a-cat-78ac7.appspot.com',
    iosBundleId: 'com.example.findACat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnBDsmWSWOoZAHTgRrKNGUKPhkmhPWF_U',
    appId: '1:681779716913:ios:3c2ae28bd1a5844ce04610',
    messagingSenderId: '681779716913',
    projectId: 'find-a-cat-78ac7',
    storageBucket: 'find-a-cat-78ac7.appspot.com',
    iosBundleId: 'com.example.findACat.RunnerTests',
  );
}
